## Scraping English Premier League standings from Wikipedia using BeautifulSoup

In [120]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [121]:
url = 'https://en.wikipedia.org/wiki/2020%E2%80%9321_Premier_League'
response = requests.get(url)

In [122]:
soup = BeautifulSoup(response.content, 'lxml')

In [123]:
league_tables = soup.findAll('table', class_='wikitable')

In [144]:
rows = league_tables[3].findAll('tr')
#rows

In [145]:
df_list = []
keys = []
dict_row = {}

for index, row in enumerate(rows):
    elements = row.findAll('th')
    #print(elements)
    
    if index == 0:
        for ele in elements:
            keys.append(ele.text[:-1])
        print(keys)
        #dict_row = {key: None for key in keys}   
        #print(dict_row)
    else:
        elements = row.findAll(['td', 'th'])
        #dict_row = {}
        for index2, element in enumerate(elements):
            dict_row[keys[index2]] = element.text[:-1]
        #print(dict_row)
        df_list.append(dict_row.copy()) #must copy() because append() inserts a reference, otherwise need to initialize with every row

['Pos', 'Team', 'Pld', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Qualification or relegation']

In [146]:
#df_list

In [147]:
df = pd.DataFrame(df_list)
df

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,1,Manchester City (C),38,27,5,6,83,32,+51,86,Qualification for the Champions League group s...
1,2,Manchester United,38,21,11,6,73,44,+29,74,Qualification for the Champions League group s...
2,3,Liverpool,38,20,9,9,68,42,+26,69,Qualification for the Champions League group s...
3,4,Chelsea,38,19,10,9,58,36,+22,67,Qualification for the Champions League group s...
4,5,Leicester City,38,20,6,12,68,50,+18,66,Qualification for the Europa League group stag...
5,6,West Ham United,38,19,8,11,62,47,+15,65,Qualification for the Europa League group stag...
6,7,Tottenham Hotspur,38,18,8,12,68,45,+23,62,Qualification for the Europa Conference League...
7,8,Arsenal,38,18,7,13,55,39,+16,61,
8,9,Leeds United,38,18,5,15,62,54,+8,59,
9,10,Everton,38,17,8,13,47,48,−1,59,
10,11,Aston Villa,38,16,7,15,55,46,+9,55,
11,12,Newcastle United,38,12,9,17,46,62,−16,45,
12,13,Wolverhampton Wanderers,38,12,9,17,36,52,−16,45,
13,14,Crystal Palace,38,12,8,18,41,66,−25,44,
14,15,Southampton,38,12,7,19,47,68,−21,43,
15,16,Brighton & Hove Albion,38,9,14,15,40,46,−6,41,
16,17,Burnley,38,10,9,19,33,55,−22,39,
17,18,Fulham (R),38,5,13,20,27,53,−26,28,Relegation to the EFL Championship
18,19,West Bromwich Albion (R),38,5,11,22,35,76,−41,26,Relegation to the EFL Championship
19,20,Sheffield United (R),38,7,2,29,20,63,−43,23,Relegation to the EFL Championship

In [148]:
df.to_csv("EPL_Standings.csv", index=False)